steps:
  # Build React (Vite) frontend
  - name: "gcr.io/cloud-builders/docker"
    dir: "frontend"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/react-frontend", "."]

  # Build ASP.NET backend
  - name: "gcr.io/cloud-builders/docker"
    dir: "backend"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/backend-api", "."]

  # Deploy frontend to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - run
      - deploy
      - react-frontend
      - "--image"
      - "gcr.io/$PROJECT_ID/react-frontend"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "80"

  # Deploy backend to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    args:
      - run
      - deploy
      - backend-api
      - "--image"
      - "gcr.io/$PROJECT_ID/backend-api"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "8080"

images:
  - "gcr.io/$PROJECT_ID/react-frontend"
  - "gcr.io/$PROJECT_ID/backend-api"
